### ISSUE TITLE
EfficientNet-B0 performance do not matched its original paper

### ISSUE THREAD

**Issue by Kuanch** [huawei-noah/ghostnet#10]
Hi, cheers for your amazing art!

I noticed that EfficientNet-B0 seems to have accuracy higher than 77%, but only about 76.3% according to Figure 6.
I wonder what causes this difference, is that the EfficientNet result could't be reproducible?

<img width="658" alt="efficientnet benchmark" src="https://user-images.githubusercontent.com/42059373/75844055-e81daa00-5e0f-11ea-8dd7-e240b74ccaa9.png">
<img width="317" alt="ghostnet fig6" src="https://user-images.githubusercontent.com/42059373/75844200-40ed4280-5e10-11ea-9951-87609520f0a9.png">

thanks for your kindly guidance.

**Comment by iamhankai** [comment]
The `76.3%` is from the official version of ICML2019 paper: http://proceedings.mlr.press/v97/tan19a/tan19a.pdf

![image](https://user-images.githubusercontent.com/9500784/75852989-20c97d80-5e28-11ea-9a2b-cbf938732632.png)

**Comment by Kuanch** [comment]
Forgive my incautiousness, thank you!
