### ISSUE TITLE
 Different levels of computational complexity

### ISSUE THREAD

**Issue by YUHAN666** [huawei-noah/ghostnet#11]
Hi,
Thanks for your explicit work.
May I ask how to set the arguments to realize different levels of computational complexity, like 0.5×, 1.0×, 1.3×?

**Comment by iamhankai** [comment]
Set `width` in https://github.com/huawei-noah/ghostnet/blob/4ccf0993cec68a0b04faeea3271a14b453a96d9b/main.py#L98

**Comment by YUHAN666** [comment]
Thank you.
