### ISSUE TITLE
kernel size in primary convolution of Ghost module

### ISSUE THREAD

**Issue by YUHAN666** [huawei-noah/ghostnet#12]
Hi, 
It is said in your paper that **the primary convolution in Ghost module can have customized kernel
size**, which is a major difference from existing efficient convolution schemes. However, it seems that in this code all the kernel size of **primary convolution in Ghost module** are set to [1, 1], and the **kernel** set in **_CONV_DEFS_0** are only used in blocks of stride=2. Is it set intentionally?

**Comment by iamhankai** [comment]
The code is not clean enough. `kernel` set in _CONV_DEFS_0 for bottleneck of stride=1 is useless.

**Comment by YUHAN666** [comment]
So the kernel size of primary convolution in Ghost module is fixed to [1, 1] by default?

**Comment by YUHAN666** [comment]
https://github.com/huawei-noah/ghostnet/blob/4ccf0993cec68a0b04faeea3271a14b453a96d9b/ghost_net.py#L288-L289
https://github.com/huawei-noah/ghostnet/blob/4ccf0993cec68a0b04faeea3271a14b453a96d9b/ghost_net.py#L270-L271

**Comment by iamhankai** [comment]
Yes,  the kernel size of primary convolution in Ghost module is fixed to [1, 1] by default.

**Comment by YUHAN666** [comment]
Have you tried with larger size?

**Comment by DYJ1234567890** [comment]
> Have you tried with larger size?

I have the same question

**Comment by iamhankai** [comment]
@YUHAN666 @DYJ1234567890 Not yet.

**Comment by DYJ1234567890** [comment]
@YUHAN666 Have you tried with larger size?

**Comment by YUHAN666** [comment]
@DYJ1234567890 Not yet, but when applied on my own project, the GhostNet trained with default setting of this code has the best performance among all the backbone I have tried.
