### ISSUE TITLE
ratio is always 1，the stride slice do nothing

### ISSUE THREAD

**Issue by sunzhe09** [huawei-noah/ghostnet#13]
after train by myself，I convert to tflite。found the strideslice don‘t change the channel，then I found in the Ghostmodel channel_mult is always equal ratio-1(2-1=1),so filters-init_channels=0.the strideslice is useless

**Comment by iamhankai** [comment]
Please describe your question more clear. What's `stride slice`?

**Comment by sunzhe09** [comment]
@iamhankai  it was this line  in myconv2d.py : dw1 = dw1[:,:,:,:filters-init_channels] if data_format=='NHWC' else dw1[:,:filters-init_channels,:,:]     I found the filters-init_channels is always 0,so this slice operator is useless

**Comment by iamhankai** [comment]
You are right, `filters-init_channels` is useless when ratio==2, but it's for robustness when ratio>2.
