### ISSUE TITLE
Faster R-CNN use GhostNet

### ISSUE THREAD

**Issue by S0soo** [huawei-noah/ghostnet#15]
I replaced the backbone network of Faster R-CNN with GhostNet and modified the structure of GhostNet, so I did not use the pre-training file you provided. This makes my model fail to converge. Can you share your experience in setting the hyperparameters? thank you

**Comment by iamhankai** [comment]
For object detection, you'd better use pretrained weights in backbone. Otherwise, it may fail to converge.

**Comment by S0soo** [comment]
Thanks i will try again
