### ISSUE TITLE
Can I only replace the Conv2d in my net with GhostModule rather than use the GhostNet?

### ISSUE THREAD

**Issue by DYJ1234567890** [huawei-noah/ghostnet#16]
Can I only replace the Conv2d in my net with GhostModule rather than use the GhostNet?

**Comment by iamhankai** [comment]
Sure. We have experiments only replacing the Conv2d in VGG-16, ResNet in our paper.

**Comment by DYJ1234567890** [comment]
Thanks for your quick response.
