### ISSUE TITLE
ghostnet is more efficient for object detection？

### ISSUE THREAD

**Issue by ronjian** [huawei-noah/ghostnet#17]
论文的实验结果中，ghostnet在分类任务中用和mobilenetv3相当的FLOPs做到几乎同样的准确率，而在检测任务中用更加少的FLOPs就可以做到和mobilenetv3同样的准确率。请问这个现象怎么解释？

分类：
| Model | FLOPs | Top-1 Acc (%) |
| ------ | ------- | ------------- |
| MobileNetV3 Large 1.0× | 219 | 75.2 |
| GhostNet 1.3× | 226 | 75.7 |

检测：
| Backbone | Detection Framework | Backbone FLOPs | mAP | 
| ----- | --- | --- | --- |
| MobileNetV3 1.0× | Faster R-CNN | 219M | 26.9% | 
| GhostNet 1.1× | Faster R-CNN | 164M| 26.9%|

**Comment by iamhankai** [comment]
ImageNet上面，Top1 acc 75.7比75.2高0.5，已经是较大的提升了。可以参考一些NAS的论文，提升0.1, 0.2就不错了:stuck_out_tongue:

**Comment by ronjian** [comment]
> ImageNet上面，Top1 acc 75.7比75.2高0.5，已经是较大的提升了。可以参考一些NAS的论文，提升0.1, 0.2就不错了😛

有道理，想问下有没有GhostNet 1.1×在分类任务上的实验结果？

**Comment by iamhankai** [comment]
About 74.5%
