### ISSUE TITLE
why video memory increase

### ISSUE THREAD

**Issue by PJJie** [huawei-noah/ghostnet#18]
Excuse me, why I used your GhostModule, but the video memory increased. I simply experimented, turning a channel number of 64 into a channel number of 128 through convolution, and the program showed increased video memory. Is the number of channels too small to fit, or the number of ghostmodules is not enough, thank you for your answer.

**Comment by iamhankai** [comment]
The run-time GPU memory may increase because Ghost module need to cache the primary feature maps and ghost feature maps and then concat them.

**Comment by PJJie** [comment]
> The run-time GPU memory may increase because Ghost module need to cache the primary feature maps and ghost feature maps and then concat them.

Thank you for your answer, so this reduction in network parameters will reduce memory, but may increase video memory. Do the benefits outweigh the disadvantages?

**Comment by iamhankai** [comment]
The main benefit of Ghost module is the latency and storage reduction. The run-time memory won't increase much.

**Comment by PJJie** [comment]
> The main benefit of Ghost module is the latency and storage reduction. The run-time memory won't increase much.

Does reducing latency mean that the training speed is increased?

**Comment by iamhankai** [comment]
I mean reducing latency during inference. We don't care about the training speed if it's not very slow.
