### ISSUE TITLE
idea similar to dense-net?

### ISSUE THREAD

**Issue by shawnthu** [huawei-noah/ghostnet#20]
To my understanding, suppose input feature map with shape (C, H, W), 
for ordinary convolution:
    output shape: (D, H, W), here suppose output D channels

while for ghost op, suppose ratio=2:
    1. first, with ordinary convolution, input (C, H, W), output (D / 2, H, W),
    2. second, still with ordinary convolution, input (D / 2, H, W), output (D / 2, H, W)
    3. concatenate the above 2 output, then get final output (D, H, W)
here omit batch normalization, relu etc. for simplicity. The above three ops final reach almost the same effect with Densenet, though the motivation is different.

Please correct me if I have any misunderstanding.

**Comment by chazdada** [comment]
The first step is right.，but the input of the second step is the feature map produced in the first step. Then concatenate the above two output as output, then get final output (D, H, W)

**Comment by shawnthu** [comment]
For DenseNet:
input: x
output: [x, conv(x)], which is fed into the following module. Here [] denotes concatenate.

For GhostNet:
input: x
first: y = conv(x)
second: z = conv(y)
output: [y, z]
I mean that the first and second operations are dense connect.

Please correct me if I'm wrong.
