### ISSUE TITLE
关于对线性变换的一些问题

### ISSUE THREAD

**Issue by MARD1NO** [huawei-noah/ghostnet#22]
作者您好，首先恭喜这篇工作中了CVPR
我对Ghost模块的理解是，先对原始特征图A做常规的卷积得到特征图B，再对特征图B做分组卷积得到其他特征图C，最后特征图B,C concat到一起进入到下一层
我想的是您文中说的这部分是个线性变换，但是您还是在对特征图B分组卷积后进行了一次Relu激活，加入激活函数不就是打破了线性吗，这不应该是一个线性变换。
望作者能解答一下

**Comment by iamhankai** [comment]
relu也可以放到concat之后做，我们放到前面是为了降低latency。
