### ISSUE TITLE
The question of formula (5) in the thesis

### ISSUE THREAD

**Issue by QFaceblue** [huawei-noah/ghostnet#23]
Formula (5) is as follows:
![image](https://user-images.githubusercontent.com/30135784/79820526-08ed8f00-83bf-11ea-9bfc-dc1416531504.png)
I think there is an error in the calculation of the parameters of the depth separable convolution part of the denominator. The correct formula should be as follows:
![image](https://user-images.githubusercontent.com/30135784/79820637-45b98600-83bf-11ea-9e3c-55ee06e00419.png)

**Comment by iamhankai** [comment]
You're right. We have corrected it in the updated version: https://arxiv.org/pdf/1911.11907.pdf
