### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by lishuai666-li** [huawei-noah/ghostnet#24]
我已经下载了这个文档，但是不知道怎么用，还有就是那个pytorch版本为什么比这个tensorflow版本内容少那么多，刚入门不太懂，这个文档下载下来以后可以做一些迁移学习吗？刚入门的同学能用明白吗？

**Comment by iamhankai** [comment]
入门教程：
- https://pytorch.org/ 
- https://www.tensorflow.org/learn
