### ISSUE TITLE
Replace Conv2d in my network, however it becomes slower, why?

### ISSUE THREAD

**Issue by FunkyKoki** [huawei-noah/ghostnet#26]
Above all, thanks for your great work! It really inspires me a lot! But now I have a question.

I replace all the `Conv2d` operations in my network except the final ones, the model parameters really becomes much more less.
However, when testing, I found that the average forward time decreases a lot by the replacement (from 428FPS down to 354FPS). 
So, is this a normal phenomenon? Or is this because of the `concat` operation?

**Comment by iamhankai** [comment]
More details? Which toolkit/hardware did you use? 

We test GhostNet on ARM with TFLite.

**Comment by FunkyKoki** [comment]
Thanks for your reply!
I test the model on Intel i7 CPU with RTX 1080 Ti. The framework I am using is PyTorch(1.2), cuda10.1 is used by the way.
The basic model structure is ReCombinator network as `https://github.com/SinaHonari/RCN`

**Comment by TheGreatWizards** [comment]
Same question,I tested under the Darknet framework, and it will be faster when using the CPU, but it will be much slower when using the GPU.

**Comment by iamhankai** [comment]
> Same question,I tested under the Darknet framework, and it will be faster when using the CPU, but it will be much slower when using the GPU.

Your observation is normal. Ghost module is more suitable for ARM/CPU, and not friendly for GPU due to the Depthwise Conv.

**Comment by FunkyKoki** [comment]
> > Same question,I tested under the Darknet framework, and it will be faster when using the CPU, but it will be much slower when using the GPU.
> 
> Your observation is normal. Ghost module is more suitable for ARM/CPU, and not friendly for GPU due to the Depthwise Conv.

thanks!

**Comment by TheGreatWizards** [comment]
Thank you for your answer. After using GhostMoudle, I found that the detection speed has slowed down. This has troubled me for a long time.
