### ISSUE TITLE
replace conv2d with GhostModule in crnn， the test accuracy decrease...

### ISSUE THREAD

**Issue by 123chengbo** [huawei-noah/ghostnet#30]
the crnn repo i used：https://github.com/Sierkinhane/crnn_chinese_characters_rec
I replace conv2d with GhostModule in the cnn part，then train with my data， same epoch（100）， the  test accuracy is lower than the original conv2d（0.9824 vs 0.9879）， Is this normal？

**Comment by iamhankai** [comment]
Sure, it's normal. The accuracy drop is very small, compared to the large FLOPs reduction.

**Comment by huyi1998** [comment]
> 

可以看看你用ghost替换conv2d的代码么

**Comment by huyi1998** [comment]
> 我用的crnn repo：https://github.com/Sierkinhane/crnn_chinese_characters_rec 我在 cnn 部分用 GhostModule 替换了 conv2d，然后用我的数据进行训练，相同的 epoch（100），测试精度低于原来的 conv2d（0.9824 vs 0.9879），这正常吗？

可以看看你用ghost替换conv2d的代码么

**Comment by iamhankai** [comment]
https://github.com/huawei-noah/Efficient-AI-Backbones/blob/master/ghostnet_pytorch/ghost_resnet.py
