### ISSUE TITLE
On the method of feature visualization

### ISSUE THREAD

**Issue by fupiao1998** [huawei-noah/ghostnet#31]
Thank you for the open source code. Here I would like to ask what method is used to visualize the feature map in figure 1 of the paper. I look forward to your reply！

**Comment by iamhankai** [comment]
```
import matplotlib.pyplot as plt
plt.imshow(image)
```

**Comment by fupiao1998** [comment]
Fine, this did not help my question, I think it’s better for me to study the answer by myself
