### ISSUE TITLE
 I have troubles when i using the pre-trained parameters, any one can help?

### ISSUE THREAD

**Issue by Geroge-W** [huawei-noah/ghostnet#37]
Hi, very thanks for your working, @iamhankai 

but i have troubles when i using the pre-trained parameters, the result of the end_points['Conv2d_18'] was [[[[0,0,0...,0,0]]]] and the front vectors were allright. could u tell me how to solving this? thanks again!
(tf==1.14.0,python==3.6, tensorpack==0.10.1)

**Comment by iamhankai** [comment]
The code was verified on Python3.6, TensorFlow-1.13.1, Tensorpack-0.9.7.

**Comment by Geroge-W** [comment]
> The code was verified on Python3.6, TensorFlow-1.13.1, Tensorpack-0.9.7.

ok， thanks for your prompt reply, i have deal with the this problem, and could u release more pretrined models with tf?

**Comment by iamhankai** [comment]
> > The code was verified on Python3.6, TensorFlow-1.13.1, Tensorpack-0.9.7.
> 
> ok， thanks for your prompt reply, i have dealt with this problem, and could u release more pretrined models with tf? @iamhankai

We moved to Pytorch :)

**Comment by Geroge-W** [comment]
> > > The code was verified on Python3.6, TensorFlow-1.13.1, Tensorpack-0.9.7.
> > 
> > 
> > ok， thanks for your prompt reply, i have dealt with this problem, and could u release more pretrined models with tf? @iamhankai
> 
> We moved to Pytorch :)

thanks, I'm going to Fine-Tune this pre-trained model, but when i using the trainer of "SingleCostTrainer()" , it arise "TypeError: Can't instantiate abstract class SingleCostTrainer with abstract methods _setup_graph", so, would you mind to sharing the training code ? , my email is 960522750@qq.com. thanks again! @iamhankai

**Comment by iamhankai** [comment]
It needs several approval procedures to transfer the code from company to github. So I recommend you to refer to the code for training:
https://github.com/tensorpack/tensorpack/blob/master/examples/ImageNetModels/shufflenet.py
