### ISSUE TITLE
MAC and parameter count on Ghostnet

### ISSUE THREAD

**Issue by anmarques** [huawei-noah/ghostnet#40]
I have tried to implement Ghostnet myself on Tensorflow and I get about 3.7M parameters and about 138M MAC. Can you confirm that I should expect 5.2M parameters and 141M MAC?

**Comment by iamhankai** [comment]
I guess you didn't include SE module?

**Comment by anmarques** [comment]
Thanks for the response.

I did include the SE module. At any rate, SE has very little impact on number of parameters and MAC count, so I don't thin they could justify the difference.

I did realize in your TF code that you use both depthwise and 1x1 conv in the residual branch, even if stride=1. That did make a difference in MAC count. I now get 145M MAC. But I'm still at 3.76M parameters. Any other thoughts?

**Comment by anmarques** [comment]
Nevermind, I did find the error. Thanks for the attention.
