### ISSUE TITLE
Bloated model

### ISSUE THREAD

**Issue by sidSingla** [huawei-noah/ghostnet#41]
Hi, 
I am using Ghostnet backbone for training YoloV3 model in Tensorflow, but I am getting a bloated model. The checkpoint data size is approx. 68MB, but the checkpoint given here is of approx 20MB https://github.com/huawei-noah/ghostnet/blob/master/tensorflow/models/ghostnet_checkpoint.data-00000-of-00001

I am also training EfficientNet model with YoloV3 and that seems to be working fine, without any bloated size.

Could anyone or the author please confirm if this is the correct architecture or anything seems weird?
I have attached the Ghostnet architecture file out of the code.

Thanks.
[ghostnet_model_arch.txt](https://github.com/huawei-noah/ghostnet/files/5455447/ghostnet_model_arch.txt)

**Comment by iamhankai** [comment]
The architecture seems correct. Did you save optimizer in your checkpoint?

**Comment by sidSingla** [comment]
Hi @iamhankai 

Thanks for the reply. Yes, optimiser is being saved in the checkpoint, but the code is doing same for the EfficientNet + YoloV3 also, and the size of model ckpt data file is 21MB only. 
I experimented with removing the optimiser variables and saved trainable_variables only instead of global_variables and the size reduced from 68 to 47MB, which is still very large.

Thanks,
Sidharth

**Comment by iamhankai** [comment]
The model size of GhostNet-1.0x is about 20MB. I guess the extra 27MB is YoloV3 head? But EfficientNet + YoloV3 is only 21MB, so it's not normal.

**Comment by sidSingla** [comment]
My bad, I was experimenting with different things and 47MB was the size of the ckpt file on removing SELayer but using globar variables. The file was not deleted.
On using SE Layer, and storing trainable variables in the ckpt file, size is 18MB. 
On storing global variables in the ckpt file, it is 68MB. Could you tell please, why the gloal variables are bloating the model so much?

Thanks a lot.

**Comment by iamhankai** [comment]
I'm also not clear why...

**Comment by sidSingla** [comment]
Sure, Thanks a lot for the help.
