### ISSUE TITLE
No speed up after using GhostModule!!

### ISSUE THREAD

**Issue by sevenHsu** [huawei-noah/ghostnet#42]
Thanks you guys' work a lot firstly.
I replaced the BasicBlock in ResNet18 with the GhostModule,but the inference processs cost more time after using it with GPU.It worked as the paper shows with CPU. Is this reasonable??

**Comment by iamhankai** [comment]
Ghost module works well on CPU. It may be slower on GPU since it consists of many depthwise convolutions.

**Comment by sevenHsu** [comment]
> Ghost module works well on CPU. It may be slower on GPU since it consists of many depthwise convolutions.

Thanks,I get it. Also Cuz the CBR module is splitted into two steps(primary Conv and cheap operation) which cust more time on CPU.

**Comment by iamhankai** [comment]
Testing CNNs using NCNN or TFLite can have an optimized inference speed for deployment.
