### ISSUE TITLE
yolov3和Darknet結合：Darknet5003中的Conv2d全部替換成Ghost Module

### ISSUE THREAD

**Issue by nnzy11** [huawei-noah/ghostnet#43]
您好，我想問一下使用的預訓練的權重文件應該是yolov3還是Ghostnet的呢，期待您的回復！

**Comment by iamhankai** [comment]
替换为Ghost module后，backbone要先预训练一下吧。

**Comment by nnzy11** [comment]
> 替换为Ghost module后，backbone要先预训练一下
好的 謝謝  想再問一下 替換Darknet中的Conv2d是權重初始化部分也要替換嗎，如果替換的話似乎出現了點問題。

**Comment by iamhankai** [comment]
权重初始化就用kaiming_normal就行，然后在imagenet预训练一下。
