### ISSUE TITLE
GhostNet is way much slower than mobilenetV1?

### ISSUE THREAD

**Issue by somewhat998** [huawei-noah/ghostnet#47]
When I test Ghostnet (drop all SE-modules) and mobilenetv1 on caffe and TensorRT, it shows that Ghostnet is  2 times slower than mobilenet. Is it because there are too many convs in ghostnet model?

**Comment by iamhankai** [comment]
Which hardware platform did you run on? CPU, GPU or TPU?

GhostNet is friendly to CPU, but not well on GPU.

**Comment by somewhat998** [comment]
@iamhankai it runs on GTX1080,  but i wonder the performance of ghostnet on some ai chips.
