### ISSUE TITLE
Pretrained model can't be loaded?

### ISSUE THREAD

**Issue by dulibubai** [huawei-noah/ghostnet#49]
what's the version of your Pytorch? when I load the pretrained model,it will exits error:
_pickle.UnpicklingError: invalid load key, '
'.

**Comment by iamhankai** [comment]
https://github.com/huawei-noah/ghostnet/tree/master/pytorch/models

**Comment by dulibubai** [comment]
@iamhankai   But I can't load the pretrained model,Is it because of the diff of the version of Pytorch?  Looking forward to your reply! Thanks

**Comment by iamhankai** [comment]
Pytorch 1.0
