### ISSUE TITLE
Undefined name 'DepthConv' in myconv2d.py

### ISSUE THREAD

**Issue by cclauss** [huawei-noah/ghostnet#5]
[flake8](http://flake8.pycqa.org) testing of https://github.com/huawei-noah/ghostnet on Python 3.8.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./myconv2d.py:23:1: F822 undefined name 'DepthConv' in __all__
__all__ = ['DepthConv', 'GhostModule']
^
1     F822 undefined name 'DepthConv' in __all__
1
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

**Comment by iamhankai** [comment]
Thanks for your remind. I have update the code: https://github.com/huawei-noah/ghostnet/commit/4ccf0993cec68a0b04faeea3271a14b453a96d9b

**Comment by cclauss** [comment]
Thank you.
