### ISSUE TITLE
读论文和程序遇到的一些疑惑。期待您的解惑，谢谢。

### ISSUE THREAD

**Issue by AnkiDord** [huawei-noah/ghostnet#50]
您好，最近我读完这篇论文，我想请教几个问题1.程序中使用Ghost Bottleneck完成标准卷积和廉价变换。文中说Ghost module就可以完成(是在程序中一个Ghost Module第一卷积是标准卷积，第二卷积中去掉激活函数么)。2.程序中的恒等变换指的是满足条件的shortcut么。期待您的解惑，谢谢。

**Comment by iamhankai** [comment]
1. Ghost Bottleneck包含2个Ghost module
2. 恒等变换用nn.Identity()实现。
