### ISSUE TITLE
线性的变换  为什么d*d呢      那不就仍是卷积？卷积核是d*d？

### ISSUE THREAD

**Issue by henbucuoshanghai** [huawei-noah/ghostnet#51]

**Comment by henbucuoshanghai** [comment]
![Uploading image.png…]()

**Comment by iamhankai** [comment]
我们这里Depthwise卷积只是实现线性变换的一种方式，可以改成其他线性变换。

**Comment by henbucuoshanghai** [comment]
后面cheap就是mobilenet1里面的 深度分离卷积 ？好像明白了



首页的cat图片&nbsp; &nbsp; &nbsp;特征图可视化，请问怎样操作的呢？

**Comment by iamhankai** [comment]
你的图挂了。。

**Comment by henbucuoshanghai** [comment]
图  里面是截取的原文那句话    说到cheap细节哪一块  直接说是d*d实现的，就二句话。  不太懂。。

**Comment by henbucuoshanghai** [comment]
特征图可视化，请问怎样操作的呢？

**Comment by iamhankai** [comment]
特征可视化，就把每个channel取出来，用matplotlib可视化一下。
