### ISSUE TITLE
pytorch运行问题

### ISSUE THREAD

**Issue by wj51** [huawei-noah/ghostnet#54]
运行不能读取label文件，验证结果很低，请问pytorch的版本validate.py是不完整吗，还是验证集不对呢

**Comment by iamhankai** [comment]
代码我们自己验证过的，应该是你验证集不对吧

**Comment by wj51** [comment]
感谢回复，我用的是ILSVRC2012_img_val，一共50000张的哪个



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai Han"<notifications@github.com&gt;; 
发送时间: 2020年12月23日(星期三) 中午11:31
收件人: "huawei-noah/ghostnet"<ghostnet@noreply.github.com&gt;; 
抄送: "打不倒的小乖兽"<2099409768@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [huawei-noah/ghostnet] pytorch运行问题 (#54)





 
代码我们自己验证过的，应该是你验证集不对吧

**Comment by iamhankai** [comment]
我们也是这个，你有什么改动吗

**Comment by wj51** [comment]
环境用的python3.6.8 torch1.3.0。其他并没有改动，代码调试loader全是1，并没有读取所有label





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/ghostnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 晚上9:16
收件人:&nbsp;"huawei-noah/ghostnet"<ghostnet@noreply.github.com&gt;;
抄送:&nbsp;"k2"<2099409768@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huawei-noah/ghostnet] pytorch运行问题 (#54)





 
我们也是这个，你有什么改动吗
