### ISSUE TITLE
The Flops seem to be larger than 141M.

### ISSUE THREAD

**Issue by luogen1996** [huawei-noah/ghostnet#55]
Thanks for your great work. I' ve run this [code](https://github.com/hszhao/SAN/blob/master/tool/counter.py)  to calculate both parameters and flops of GhostNet. The results are as following:
Params/Flops: 5.18 M/0.1512 GMac
The Flops seem to be larger than 141M (151M in my test).  So I want to know what causes the difference between this result and yours? Thanks !

**Comment by iamhankai** [comment]
The BN layer is fused into Conv2d after training, so the FLOPs of BN can be ignored for inference.

**Comment by luogen1996** [comment]
> The BN layer is fused into Conv2d after training, so the FLOPs of BN can be ignored for inference.

Thank your for you reply!
