### ISSUE TITLE
Can more pretrained model(TF) be released?

### ISSUE THREAD

**Issue by Zhengtq** [huawei-noah/ghostnet#6]
I find that in this repo, there is only a pretrained TF model with width ratio 1. Can more pretrained models with diverse width ratio(such as 0.75, 0.5, etc..) to be provided?
Thanks.

**Comment by Alicture** [comment]
@Zhengtq How to transform those .index .data file into pb?

**Comment by Zhengtq** [comment]
@Alicture 
` output_graph_def = convert_variables_to_constants(sess, sess.graph_def, output_node_names)
with tf.gfile.GFile( 'graph.pb', "wb") as f:
          f.write(output_graph_def.SerializeToString())
`

**Comment by iamhankai** [comment]
Hi all, we released pytorch pretrained model.

**Comment by Zhengtq** [comment]
Can Tensorflow pretrained model be realsed? Thanks.

**Comment by iamhankai** [comment]
We are preparing to release the training code of Pytorch.

**Comment by iamhankai** [comment]
More models are released on MindSpore Hub: https://www.mindspore.cn/resources/hub/details?639/noah-cvlab/gpu/1.0/ghostnet_v1.0_oxford_pets
