### ISSUE TITLE
Implementation of Ghost-VGG-16 for CIFAR10

### ISSUE THREAD

**Issue by lld533** [huawei-noah/ghostnet#61]
Hi there,

Thanks for sharing your code. I'm trying to implement GhostNet under VGG-16 (i.e., Ghost-VGG-16) on CIFAR10 but I find my FLOPs (858.282k) and number of parameters (18.657536M) are far fewer than what are reported (FLOPs: 15M, Total Params: 313M) in the CVPR2020 paper. I use PyTorch.

For example, I replace each nn.Conv2d in the original VGG-16 (https://github.com/kuangliu/pytorch-cifar/blob/master/models/vgg.py) with GhostModule (the one used to build GhostNet for ImageNet) to build up Ghost-VGG-16. I use torchsummaryX to count overhead and number of parameters.

Below plz find my current implementation. Could you please correct me? Many thanks in advance!

```
import torch
import torch.nn as nn
import math


cfg = {
    'VGG11': [64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M'],
    'VGG13': [64, 64, 'M', 128, 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M'],
    'VGG16': [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M'],
    'VGG19': [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 256, 'M', 512, 512, 512, 512, 'M', 512, 512, 512, 512, 'M'],
}


class GhostModule(nn.Module):
    def __init__(self, inp, oup, kernel_size=1, ratio=2, dw_size=3, stride=1, relu=True):
        super(GhostModule, self).__init__()
        self.oup = oup
        init_channels = math.ceil(oup / ratio)
        new_channels = init_channels*(ratio-1)

        self.primary_conv = nn.Sequential(
            nn.Conv2d(inp, init_channels, kernel_size, stride, kernel_size//2, bias=False),
            nn.BatchNorm2d(init_channels),
            nn.ReLU(inplace=True) if relu else nn.Sequential(),
        )

        self.cheap_operation = nn.Sequential(
            nn.Conv2d(init_channels, new_channels, dw_size, 1, dw_size//2, groups=init_channels, bias=False),
            nn.BatchNorm2d(new_channels),
            nn.ReLU(inplace=True) if relu else nn.Sequential(),
        ) 

    def forward(self, x):
        x1 = self.primary_conv(x)
        x2 = self.cheap_operation(x1)
        out = torch.cat([x1,x2], dim=1)
        return out[:,:self.oup,:,:]

class VGG(nn.Module):
    def __init__(self, vgg_name):
        super(VGG, self).__init__()
        self.features = self._make_layers(cfg[vgg_name])
        self.classifier = nn.Linear(512, 10)

    def forward(self, x):
        out = self.features(x)
        out = out.view(out.size(0), -1)
        out = self.classifier(out)
        return out

    def _make_layers(self, cfg):
        layers = []
        in_channels = 3
        for x in cfg:
            if x == 'M':
                layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
            else:
                layers += [GhostModule(in_channels, x),
                           nn.BatchNorm2d(x),
                           nn.ReLU(inplace=True)]
                in_channels = x
        layers += [nn.AvgPool2d(kernel_size=1, stride=1)]
        return nn.Sequential(*layers)

from torchsummaryX import summary

net = VGG('VGG16')
x = torch.randn(2,3,32,32)
summary(net, x)
```

**Comment by iamhankai** [comment]
```
layers += [GhostModule(in_channels, x),
                           nn.BatchNorm2d(x),
                           nn.ReLU(inplace=True)]
```
Change it to
```
layers += [GhostModule(in_channels, x, kernel_size=3)]
```

**Comment by lld533** [comment]
> ```
> layers += [GhostModule(in_channels, x),
>                            nn.BatchNorm2d(x),
>                            nn.ReLU(inplace=True)]
> ```
> 
> Change it to
> 
> ```
> layers += [GhostModule(in_channels, x, kernel_size=3)]
> ```

Thanks for pointing out the issue. After applying the change, my FLOPs and number of parameters for Ghost-VGG-16 using torchsummaryX are now half of the reported results.
Total params            7.387818M
Mult-Adds             157.851776M

Is this right?

**Comment by iamhankai** [comment]
Bingo~

**Comment by lld533** [comment]
> > ```
> > layers += [GhostModule(in_channels, x),
> >                            nn.BatchNorm2d(x),
> >                            nn.ReLU(inplace=True)]
> > ```
> > 
> > 
> > Change it to
> > ```
> > layers += [GhostModule(in_channels, x, kernel_size=3)]
> > ```
> 
> Thanks for pointing out the issue. After applying the change, my FLOPs and number of parameters for Ghost-VGG-16 using torchsummaryX are now half of the reported results.
> Total params 7.387818M
> Mult-Adds 157.851776M
> 
> Is this right?

Great! Thanks!
