### ISSUE TITLE
作者大佬，有没有Ghost-VGG16模型的代码啊？

### ISSUE THREAD

**Issue by CCxiaoLL** [huawei-noah/ghostnet#8]

**Comment by iamhankai** [comment]
A: https://github.com/kuangliu/pytorch-cifar
B: https://github.com/iamhankai/ghostnet.pytorch/blob/9aabd96d8132aa05f2a3e40a35f5b67c019494a2/ghost_net.py#L55

A+B就是你需要的

**Comment by laisimiao** [comment]
I know what you mean after i carefully read two repos. And my question is just using GhostNet to train on cifar-10, not insert GhostModule into other backbones? So have you that cfgs or did you not try this?

**Comment by iamhankai** [comment]
You mean GhostNet on CIFAR-10? We have not trained GhostNet on CIFAR-10.

**Comment by laisimiao** [comment]
> You mean GhostNet on CIFAR-10? We have not trained GhostNet on CIFAR-10.

🆗，thank you.
